// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/api/internal/controller"
	"github.com/api/internal/service"
	"github.com/api/internal/service/auth"
)

// Injectors from wire.go:

func InitializeUserController() *controller.UserController {
	iUserService := service.NewUserService()
	userController := controller.NewUserController(iUserService)
	return userController
}

func InitializeAuthController() *controller.AuthController {
	iAuthProcessService := auth_service.NewAuthProcessService()
	iAuthService := auth_service.NewAuthService(iAuthProcessService)
	authController := controller.NewAuthController(iAuthService)
	return authController
}

func InitializeAdminController() *controller.AdminController {
	iAdminService := service.NewAdminService()
	adminController := controller.NewAdminController(iAdminService)
	return adminController
}

func InitializeMajorController() *controller.MajorController {
	iMajorService := service.NewMajorService()
	majorController := controller.NewMajorController(iMajorService)
	return majorController
}

func InitializeSubMajorController() *controller.SubMajorController {
	iSubMajorService := service.NewSubMajorService()
	subMajorController := controller.NewSubMajorController(iSubMajorService)
	return subMajorController
}
