// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/api/internal/controller"
	"github.com/api/internal/repository"
	"github.com/api/internal/service"
	"github.com/api/internal/service/auth"
)

// Injectors from wire.go:

func InitializeUserController() *controller.UserController {
	iUserRepository := repository.NewUserRepository()
	iUserService := service.NewUserService(iUserRepository)
	userController := controller.NewUserController(iUserService)
	return userController
}

func InitializeAuthController() *controller.AuthController {
	iUserRepository := repository.NewUserRepository()
	iAuthProcessService := auth_service.NewAuthProcessService()
	iAuthService := auth_service.NewAuthService(iUserRepository, iAuthProcessService)
	authController := controller.NewAuthController(iAuthService)
	return authController
}

func InitializeAdminController() *controller.AdminController {
	iUserRepository := repository.NewUserRepository()
	iStudentRepository := repository.NewStudentRepository()
	iAdminService := service.NewAdminService(iUserRepository, iStudentRepository)
	adminController := controller.NewAdminController(iAdminService)
	return adminController
}

func InitializeMajorController() *controller.MajorController {
	iMajorRepository := repository.NewMajorRepository()
	iMajorService := service.NewMajorService(iMajorRepository)
	majorController := controller.NewMajorController(iMajorService)
	return majorController
}
