// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Major struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Permission struct {
	ID   int64
	Name string
}

type Role struct {
	ID   int64
	Name string
}

type RolesPermission struct {
	ID           int64
	RoleID       int64
	PermissionID int64
}

type Semester struct {
	ID        int64
	Name      string
	StartTime time.Time
	EndTime   time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SubMajor struct {
	ID        int64
	Name      string
	MajorID   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}
