// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: student.sql

package database

import (
	"context"
)

const createStudent = `-- name: CreateStudent :exec
INSERT INTO students (code, sub_major_id, user_id)
VALUES ($1, $2, $3)
`

type CreateStudentParams struct {
	Code       string
	SubMajorID int64
	UserID     int64
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) error {
	_, err := q.db.ExecContext(ctx, createStudent, arg.Code, arg.SubMajorID, arg.UserID)
	return err
}
