// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package database

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, user_type, password, email, code, sub_major_id, capstone_group_id, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserType,
		&i.Password,
		&i.Email,
		&i.Code,
		&i.SubMajorID,
		&i.CapstoneGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, user_type, password, email, code, sub_major_id, capstone_group_id, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserType,
		&i.Password,
		&i.Email,
		&i.Code,
		&i.SubMajorID,
		&i.CapstoneGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
