basePath: /api/v1
definitions:
  admin_dto.InputAdminCreateStudentAccount:
    properties:
      code:
        type: string
      email:
        type: string
      name:
        type: string
      phone_number:
        type: string
      sub_major_id:
        type: integer
    required:
    - code
    - email
    - name
    - phone_number
    - sub_major_id
    type: object
  admin_dto.InputAdminCreateTeacherAccount:
    properties:
      email:
        type: string
      name:
        type: string
      phone_number:
        type: string
      sub_major_id:
        type: integer
    required:
    - email
    - name
    - phone_number
    - sub_major_id
    type: object
  auth_dto.InputLogin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth_dto.OutputLogin:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.MetaPagination:
    properties:
      current_page:
        type: integer
      total:
        type: integer
    type: object
  major_dto.OutputGetListMajor:
    properties:
      items:
        items:
          $ref: '#/definitions/major_dto.OutputMajor'
        type: array
      meta:
        $ref: '#/definitions/dto.MetaPagination'
    type: object
  major_dto.OutputMajor:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  response.ResponseDataSuccess:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: boolean
    type: object
  response.ResponseErr:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: boolean
    type: object
  sub_major_dto.OutputGetListMajor:
    properties:
      items:
        items:
          $ref: '#/definitions/sub_major_dto.OutputSubMajor'
        type: array
      meta:
        $ref: '#/definitions/dto.MetaPagination'
    type: object
  sub_major_dto.OutputSubMajor:
    properties:
      id:
        type: integer
      major_id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: minhbeardev@gmail.com
  description: Capstone Project FPT API
  title: Capstone Project FPT API
  version: "1.0"
paths:
  /admin/students/create-account:
    post:
      consumes:
      - application/json
      description: Admin Create Student Account
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/admin_dto.InputAdminCreateStudentAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseDataSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseErr'
      security:
      - ApiKeyAuth: []
      summary: CreateStudentAccount
      tags:
      - Admin
  /admin/teachers/create-account:
    post:
      consumes:
      - application/json
      description: Admin Create Teacher Account
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/admin_dto.InputAdminCreateTeacherAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseDataSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseErr'
      security:
      - ApiKeyAuth: []
      summary: CreateTeacherAccount
      tags:
      - Admin
  /hello-world:
    get:
      consumes:
      - application/json
      description: Hello World
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseDataSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseErr'
      security:
      - ApiKeyAuth: []
      summary: HelloWorldController
      tags:
      - Public
  /login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth_dto.InputLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseDataSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseErr'
      summary: Login
      tags:
      - Auth
  /majors:
    get:
      consumes:
      - application/json
      description: Get list major
      parameters:
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/major_dto.OutputGetListMajor'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseErr'
      summary: GetListMajor
      tags:
      - Public
  /sub-majors:
    get:
      consumes:
      - application/json
      description: Get list sub major
      parameters:
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: Major ID
        in: query
        name: major_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sub_major_dto.OutputGetListMajor'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResponseErr'
      summary: GetListSubMajor
      tags:
      - Public
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
